services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - todo

  backend:
    image: python:3.12
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - todo
  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: "user3"
      POSTGRES_PASSWORD: "qwerty"
      POSTGRES_DB: "todobase"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - todo

volumes:
  db_data:


networks:
  todo:
    name: todo
