"""add norification send field

Revision ID: ebe8482fe9c4
Revises: 0b2bfb025110
Create Date: 2024-12-10 10:24:53.502899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ebe8482fe9c4'
down_revision: Union[str, None] = '0b2bfb025110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('last_notification', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'last_notification')
    # ### end Alembic commands ###
